set(CMAKE_SYSTEM_NAME Haiku)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

find_program(HAIKU_C_COMPILER NAMES x86_64-unknown-haiku-gcc REQUIRED)
find_program(HAIKU_CXX_COMPILER NAMES x86_64-unknown-haiku-g++ REQUIRED)

set(CMAKE_C_COMPILER "${HAIKU_C_COMPILER}")
set(CMAKE_CXX_COMPILER "${HAIKU_CXX_COMPILER}")

execute_process(
    COMMAND "${CMAKE_CXX_COMPILER}" -print-sysroot
    OUTPUT_VARIABLE HAIKU_SYSROOT
    OUTPUT_STRIP_TRAILING_WHITESPACE
)

if(NOT HAIKU_SYSROOT)
    message(FATAL_ERROR "Failed to detect Haiku sysroot from ${CMAKE_CXX_COMPILER}")
endif()

set(CMAKE_SYSROOT "${HAIKU_SYSROOT}")
set(CMAKE_FIND_ROOT_PATH "${HAIKU_SYSROOT}")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
